### ISSUE TITLE
Launch as administrator

### ISSUE THREAD

**Issue by alien142** [jonathancrozier/jc-samples-windows-service-gui-launcher#3]
I was tried by add more
```
userProcess.StartInfo.UseShellExecute = true;
userProcess.StartInfo.Verb = "runas";
```
But the program after being started still doesn't have admin permission.

**Comment by jonathancrozier** [comment]
Sorry for not seeing this sooner!

It isn't possible to launch a program as an administrator from a Windows Service, as this would be a security issue.

I will close this issue for the moment, but please let me know if there's anything else I can help clarify for you.

**Comment by Transis-Felipe** [comment]
Hello Jonathan.

First, congratulations for this program.

I think teamviewer service found a way to launch a program as administrator, because when I close the Teamviewer UI and restart the service, the UI start again.

![image](https://github.com/jonathancrozier/jc-samples-windows-service-gui-launcher/assets/4941173/f034e134-656a-410c-ac50-c111a5e28048)

UI that was started by Teamviewer service

![image](https://github.com/jonathancrozier/jc-samples-windows-service-gui-launcher/assets/4941173/bcb21ffd-c1f4-4035-826e-fa17c52bf0b4)

**Comment by jonathancrozier** [comment]
Thank you, Felipe.

That's interesting, however, although the TeamViewer service is running as the 'Local System' user, is the TeamViewer UI running with administrator rights?

Sometimes when a Windows program is installed, a scheduled task will be created as part of the installation which can be triggered to launch a program with a user interface as an administrator.
